# Generated by Django 5.1.5 on 2025-01-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='Default Address', max_length=400),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='0000', max_length=15),
        ),
    ]
